export const cards = [
    {
        nombre: "El Tonto",
        name: "The Fool",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "El Mago",
        name: "The Magician",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "La Sacerdotisa",
        name: "The High Priestess",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "La Emperatriz",
        name: "The Empress",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "El Emperador",
        name: "The Emperor",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "El Hierofante",
        name: "The Hierophant",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "Los Amantes",
        name: "The Lovers",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "El Carro",
        name: "The Chariot",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "La Fuerza",
        name: "Strength",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "El Ermitaño",
        name: "The Hermit",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "La Rueda de la Fortuna",
        name: "Wheel of Fortune",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "La Justicia",
        name: "Justice",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "El Colgado",
        name: "The Hanged Man",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "La Muerte",
        name: "Death",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "La Templanza",
        name: "Temperance",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "El Diablo",
        name: "The Devil",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "La Torre",
        name: "The Tower",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "La Estrella",
        name: "The Star",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "La Luna",
        name: "The Moon",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "El Sol",
        name: "The Sun",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "El Juicio",
        name: "Judgement",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "El Mundo",
        name: "The World",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
    },
    {
        nombre: "As de Bastos",
        name: "Ace of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Dos de Bastos",
        name: "Two of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Tres de Bastos",
        name: "Three of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Cuatro de Bastos",
        name: "Four of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Cinco de Bastos",
        name: "Five of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Seis de Bastos",
        name: "Six of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Siete de Bastos",
        name: "Seven of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Ocho de Bastos",
        name: "Eight of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Nueve de Bastos",
        name: "Nine of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Diez de Bastos",
        name: "Ten of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Sota de Bastos",
        name: "Page of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Caballero de Bastos",
        name: "Knight of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Reina de Bastos",
        name: "Queen of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "Rey de Bastos",
        name: "King of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
    },
    {
        nombre: "As de Copas",
        name: "Ace of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Dos de Copas",
        name: "Two of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Tres de Copas",
        name: "Three of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Cuatro de Copas",
        name: "Four of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Cinco de Copas",
        name: "Five of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Seis de Copas",
        name: "Six of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Siete de Copas",
        name: "Seven of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Ocho de Copas",
        name: "Eight of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Nueve de Copas",
        name: "Nine of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Diez de Copas",
        name: "Ten of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Sota de Copas",
        name: "Page of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Caballero de Copas",
        name: "Knight of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Reina de Copas",
        name: "Queen of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "Rey de Copas",
        name: "King of Cups",
        categoria: "Las Copas",
        category: "The Cups",
    },
    {
        nombre: "As de Espadas",
        name: "Ace of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Dos de Espadas",
        name: "Two of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Tres de Espadas",
        name: "Three of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Cuatro de Espadas",
        name: "Four of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Cinco de Espadas",
        name: "Five of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Seis de Espadas",
        name: "Six of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Siete de Espadas",
        name: "Seven of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Ocho de Espadas",
        name: "Eight of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Nueve de Espadas",
        name: "Nine of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Diez de Espadas",
        name: "Ten of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Sota de Espadas",
        name: "Page of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Caballero de Espadas",
        name: "Knight of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Reina de Espadas",
        name: "Queen of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "Rey de Espadas",
        name: "King of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
    },
    {
        nombre: "As de Oros",
        name: "Ace of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Dos de Oros",
        name: "Two of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Tres de Oros",
        name: "Three of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Cuatro de Oros",
        name: "Four of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Cinco de Oros",
        name: "Five of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Seis de Oros",
        name: "Six of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Siete de Oros",
        name: "Seven of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Ocho de Oros",
        name: "Eight of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Nueve de Oros",
        name: "Nine of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Diez de Oros",
        name: "Ten of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Sota de Oros",
        name: "Page of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Caballero de Oros",
        name: "Knight of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Reina de Oros",
        name: "Queen of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
    {
        nombre: "Rey de Oros",
        name: "King of Coins",
        categoria: "Los Oros",
        category: "The Coins",
    },
]
