export const cards = [
    {
        nombre: "El Tonto",
        name: "The Fool",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "nuevos comienzos",
            "aventuras",
            "libertad",
            "espontaneidad",
            "potencial ilimitado",
        ],
        img: "0.jpg",
    },
    {
        nombre: "El Mago",
        name: "The Magician",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "habilidad",
            "acción",
            "manifestación",
            "voluntad",
            "transformación",
        ],
        img: "1.jpg",
    },
    {
        nombre: "La Sacerdotisa",
        name: "The High Priestess",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "intuición",
            "misterio",
            "sabiduría interior",
            "conocimiento oculto",
            "subconsciente",
        ],
        img: "2.jpg",
    },
    {
        nombre: "La Emperatriz",
        name: "The Empress",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "fertilidad",
            "abundancia",
            "naturaleza",
            "creatividad",
            "nutrición",
        ],
        img: "3.jpg",
    },
    {
        nombre: "El Emperador",
        name: "The Emperor",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "autoridad",
            "control",
            "estructura",
            "poder",
            "disciplina",
        ],
        img: "4.jpg",
    },
    {
        nombre: "El Hierofante",
        name: "The Hierophant",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "tradición",
            "religión",
            "enseñanza",
            "espiritualidad",
            "conformidad",
        ],
        img: "5.jpg",
    },
    {
        nombre: "Los Amantes",
        name: "The Lovers",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: ["amor", "unión", "decisiones", "dualidad", "armonía"],
        img: "6.jpg",
    },
    {
        nombre: "El Carro",
        name: "The Chariot",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "voluntad",
            "triunfo",
            "control",
            "determinación",
            "movimiento",
        ],
        img: "7.jpg",
    },
    {
        nombre: "La Fuerza",
        name: "Strength",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "coraje",
            "determinación",
            "energía",
            "dominio",
            "compasión",
        ],
        img: "8.jpg",
    },
    {
        nombre: "El Ermitaño",
        name: "The Hermit",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "búsqueda",
            "introspección",
            "sabiduría",
            "soledad",
            "guía interior",
        ],
        img: "9.jpg",
    },
    {
        nombre: "La Rueda de la Fortuna",
        name: "Wheel of Fortune",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: ["cambio", "ciclo", "destino", "fortuna", "movimiento"],
        img: "10.jpg",
    },
    {
        nombre: "La Justicia",
        name: "Justice",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "justicia",
            "equilibrio",
            "verdad",
            "responsabilidad",
            "causa y efecto",
        ],
        img: "11.jpg",
    },
    {
        nombre: "El Colgado",
        name: "The Hanged Man",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "sacrificio",
            "perspectiva",
            "rendición",
            "iluminación",
            "pausa",
        ],
        img: "12.jpg",
    },
    {
        nombre: "La Muerte",
        name: "Death",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "transformación",
            "final",
            "cambio",
            "renacimiento",
            "transición",
        ],
        img: "13.jpg",
    },
    {
        nombre: "La Templanza",
        name: "Temperance",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "equilibrio",
            "moderación",
            "armonía",
            "paciencia",
            "integración",
        ],
        img: "14.jpg",
    },
    {
        nombre: "El Diablo",
        name: "The Devil",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "materialismo",
            "ataduras",
            "tentación",
            "esclavitud",
            "sombra",
        ],
        img: "15.jpg",
    },
    {
        nombre: "La Torre",
        name: "The Tower",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: ["ruptura", "cambio", "revelación", "caos", "destrucción"],
        img: "16.jpg",
    },
    {
        nombre: "La Estrella",
        name: "The Star",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "esperanza",
            "inspiración",
            "renovación",
            "serenidad",
            "guía",
        ],
        img: "17.jpg",
    },
    {
        nombre: "La Luna",
        name: "The Moon",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "intuición",
            "ilusiones",
            "misterio",
            "inconsciente",
            "engaño",
        ],
        img: "18.jpg",
    },
    {
        nombre: "El Sol",
        name: "The Sun",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "éxito",
            "vitalidad",
            "energía",
            "felicidad",
            "realización",
        ],
        img: "19.jpg",
    },
    {
        nombre: "El Juicio",
        name: "Judgement",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "renacimiento",
            "juicio",
            "absolución",
            "despertar",
            "revisión",
        ],
        img: "20.jpg",
    },
    {
        nombre: "El Mundo",
        name: "The World",
        categoria: "Arcano Mayor",
        category: "Major Arcana",
        representa: [
            "completación",
            "viaje",
            "realización",
            "unidad",
            "integridad",
        ],
        img: "21.jpg",
    },
    {
        nombre: "As de Bastos",
        name: "Ace of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: [
            "inspiración",
            "potencial",
            "creatividad",
            "nuevos comienzos",
            "pasión",
        ],
        img: "22.jpg",
    },
    {
        nombre: "Dos de Bastos",
        name: "Two of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: [
            "planificación",
            "decisión",
            "exploración",
            "ambición",
            "futuro",
        ],
        img: "23.jpg",
    },
    {
        nombre: "Tres de Bastos",
        name: "Three of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: [
            "previsión",
            "oportunidades",
            "progreso",
            "expansión",
            "exploración",
        ],
        img: "24.jpg",
    },
    {
        nombre: "Cuatro de Bastos",
        name: "Four of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: ["celebración", "armonía", "hogar", "comunidad", "éxito"],
        img: "25.jpg",
    },
    {
        nombre: "Cinco de Bastos",
        name: "Five of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: [
            "conflicto",
            "competencia",
            "desafío",
            "lucha",
            "discordia",
        ],
        img: "26.jpg",
    },
    {
        nombre: "Seis de Bastos",
        name: "Six of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: ["victoria", "reconocimiento", "éxito", "triunfo", "honor"],
        img: "27.jpg",
    },
    {
        nombre: "Siete de Bastos",
        name: "Seven of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: [
            "defensa",
            "coraje",
            "persistencia",
            "desafío",
            "resistencia",
        ],
        img: "28.jpg",
    },
    {
        nombre: "Ocho de Bastos",
        name: "Eight of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: ["movimiento", "velocidad", "progreso", "acción", "viaje"],
        img: "29.jpg",
    },
    {
        nombre: "Nueve de Bastos",
        name: "Nine of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: [
            "resiliencia",
            "determinación",
            "espera",
            "resistencia",
            "protección",
        ],
        img: "30.jpg",
    },
    {
        nombre: "Diez de Bastos",
        name: "Ten of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: [
            "responsabilidad",
            "carga",
            "trabajo",
            "esfuerzo",
            "pesadez",
        ],
        img: "31.jpg",
    },
    {
        nombre: "Sota de Bastos",
        name: "Page of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: [
            "exploración",
            "entusiasmo",
            "descubrimiento",
            "aventura",
            "nuevas ideas",
        ],
        img: "32.jpg",
    },
    {
        nombre: "Caballero de Bastos",
        name: "Knight of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: ["aventura", "energía", "impulso", "audacia", "movimiento"],
        img: "33.jpg",
    },
    {
        nombre: "Reina de Bastos",
        name: "Queen of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: [
            "confianza",
            "vibrante",
            "determinación",
            "independencia",
            "atracción",
        ],
        img: "34.jpg",
    },
    {
        nombre: "Rey de Bastos",
        name: "King of Wands",
        categoria: "Los Bastos",
        category: "The Wands",
        representa: [
            "liderazgo",
            "visión",
            "poder",
            "autoridad",
            "inspiración",
        ],
        img: "35.jpg",
    },
    {
        nombre: "As de Copas",
        name: "Ace of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "amor",
            "nuevas emociones",
            "intimidad",
            "espiritualidad",
            "compasión",
        ],
        img: "36.jpg",
    },
    {
        nombre: "Dos de Copas",
        name: "Two of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "unión amorosa",
            "energía femenina y masculina",
            "alma",
            "intuición",
            "eros",
            "mente consciente",
        ],
        img: "37.jpg",
    },
    {
        nombre: "Tres de Copas",
        name: "Three of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "celebración",
            "amistad",
            "comunidad",
            "alegría",
            "reunión",
        ],
        img: "38.jpg",
    },
    {
        nombre: "Cuatro de Copas",
        name: "Four of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "meditación",
            "aburrimiento",
            "desconexión",
            "reevaluación",
            "introspección",
        ],
        img: "39.jpg",
    },
    {
        nombre: "Cinco de Copas",
        name: "Five of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "pérdida",
            "tristeza",
            "arrepentimiento",
            "duelo",
            "decepción",
        ],
        img: "40.jpg",
    },
    {
        nombre: "Seis de Copas",
        name: "Six of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "nostalgia",
            "recuerdos",
            "infancia",
            "inocencia",
            "reconciliación",
        ],
        img: "41.jpg",
    },
    {
        nombre: "Siete de Copas",
        name: "Seven of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "fantasía",
            "elecciones",
            "confusión",
            "ilusiones",
            "deseos",
        ],
        img: "42.jpg",
    },
    {
        nombre: "Ocho de Copas",
        name: "Eight of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "abandono",
            "búsqueda",
            "desilusión",
            "cambio",
            "viaje espiritual",
        ],
        img: "43.jpg",
    },
    {
        nombre: "Nueve de Copas",
        name: "Nine of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: ["satisfacción", "deseo", "gratitud", "plenitud", "éxito"],
        img: "44.jpg",
    },
    {
        nombre: "Diez de Copas",
        name: "Ten of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "felicidad",
            "armonía",
            "hogar",
            "familia",
            "amor duradero",
        ],
        img: "45.jpg",
    },
    {
        nombre: "Sota de Copas",
        name: "Page of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "creatividad",
            "intuición",
            "nuevas oportunidades",
            "emociones frescas",
            "sueños",
        ],
        img: "46.jpg",
    },
    {
        nombre: "Caballero de Copas",
        name: "Knight of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "romance",
            "propuesta",
            "imaginación",
            "idealismo",
            "mensajero",
        ],
        img: "47.jpg",
    },
    {
        nombre: "Reina de Copas",
        name: "Queen of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "compasión",
            "cuidado",
            "sensibilidad",
            "intuición",
            "emociones profundas",
        ],
        img: "48.jpg",
    },
    {
        nombre: "Rey de Copas",
        name: "King of Cups",
        categoria: "Las Copas",
        category: "The Cups",
        representa: [
            "equilibrio emocional",
            "control",
            "sabiduría",
            "compasión",
            "diplomacia",
        ],
        img: "49.jpg",
    },
    {
        nombre: "As de Espadas",
        name: "Ace of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "claridad",
            "verdad",
            "nuevas ideas",
            "victoria",
            "comunicación",
        ],
        img: "50.jpg",
    },
    {
        nombre: "Dos de Espadas",
        name: "Two of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "indecisión",
            "bloqueo",
            "estancamiento",
            "equilibrio precario",
            "negación",
        ],
        img: "51.jpg",
    },
    {
        nombre: "Tres de Espadas",
        name: "Three of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "dolor",
            "traición",
            "tristeza",
            "separación",
            "desilusión",
        ],
        img: "52.jpg",
    },
    {
        nombre: "Cuatro de Espadas",
        name: "Four of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "descanso",
            "recuperación",
            "reflexión",
            "retiro",
            "curación",
        ],
        img: "53.jpg",
    },
    {
        nombre: "Cinco de Espadas",
        name: "Five of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: ["conflicto", "derrota", "engaño", "tensión", "hostilidad"],
        img: "54.jpg",
    },
    {
        nombre: "Seis de Espadas",
        name: "Six of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "transición",
            "movimiento",
            "cambio",
            "viaje",
            "recuperación",
        ],
        img: "55.jpg",
    },
    {
        nombre: "Siete de Espadas",
        name: "Seven of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "engaño",
            "estrategia",
            "evasión",
            "subterfugio",
            "independencia",
        ],
        img: "56.jpg",
    },
    {
        nombre: "Ocho de Espadas",
        name: "Eight of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "restricción",
            "atadura",
            "confusión",
            "impotencia",
            "miedo",
        ],
        img: "57.jpg",
    },
    {
        nombre: "Nueve de Espadas",
        name: "Nine of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "ansiedad",
            "preocupación",
            "pesadilla",
            "culpa",
            "desesperación",
        ],
        img: "58.jpg",
    },
    {
        nombre: "Diez de Espadas",
        name: "Ten of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: ["traición", "final", "dolor", "colapso", "derrota"],
        img: "59.jpg",
    },
    {
        nombre: "Sota de Espadas",
        name: "Page of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "curiosidad",
            "aprendizaje",
            "observación",
            "vigilancia",
            "inteligencia",
        ],
        img: "60.jpg",
    },
    {
        nombre: "Caballero de Espadas",
        name: "Knight of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "acción",
            "impulso",
            "ambición",
            "determinación",
            "persecución",
        ],
        img: "61.jpg",
    },
    {
        nombre: "Reina de Espadas",
        name: "Queen of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "independencia",
            "claridad",
            "percepción",
            "objetividad",
            "veracidad",
        ],
        img: "62.jpg",
    },
    {
        nombre: "Rey de Espadas",
        name: "King of Swords",
        categoria: "Las Espadas",
        category: "The Swords",
        representa: [
            "autoridad",
            "verdad",
            "juicio",
            "integridad",
            "racionalidad",
        ],
        img: "63.jpg",
    },
    {
        nombre: "As de Oros",
        name: "Ace of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "prosperidad",
            "oportunidad",
            "abundancia",
            "nuevo comienzo",
            "recompensa",
        ],
        img: "64.jpg",
    },
    {
        nombre: "Dos de Oros",
        name: "Two of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "equilibrio",
            "adaptación",
            "flexibilidad",
            "prioridades",
            "cambio",
        ],
        img: "65.jpg",
    },
    {
        nombre: "Tres de Oros",
        name: "Three of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "trabajo en equipo",
            "colaboración",
            "habilidad",
            "construcción",
            "realización",
        ],
        img: "66.jpg",
    },
    {
        nombre: "Cuatro de Oros",
        name: "Four of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "estabilidad",
            "posesión",
            "control",
            "seguridad",
            "retención",
        ],
        img: "67.jpg",
    },
    {
        nombre: "Cinco de Oros",
        name: "Five of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "pérdida",
            "necesidad",
            "dificultad",
            "aislamiento",
            "escasez",
        ],
        img: "68.jpg",
    },
    {
        nombre: "Seis de Oros",
        name: "Six of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "generosidad",
            "caridad",
            "ayuda",
            "equilibrio",
            "solidaridad",
        ],
        img: "69.jpg",
    },
    {
        nombre: "Siete de Oros",
        name: "Seven of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "evaluación",
            "espera",
            "crecimiento",
            "inversión",
            "paciencia",
        ],
        img: "70.jpg",
    },
    {
        nombre: "Ocho de Oros",
        name: "Eight of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "habilidad",
            "dedicación",
            "trabajo duro",
            "artesanía",
            "maestría",
        ],
        img: "71.jpg",
    },
    {
        nombre: "Nueve de Oros",
        name: "Nine of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "independencia",
            "éxito",
            "abundancia",
            "autonomía",
            "lujo",
        ],
        img: "72.jpg",
    },
    {
        nombre: "Diez de Oros",
        name: "Ten of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "herencia",
            "estabilidad",
            "prosperidad",
            "tradición",
            "permanencia",
        ],
        img: "73.jpg",
    },
    {
        nombre: "Sota de Oros",
        name: "Page of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "nuevos comienzos",
            "estudio",
            "trabajo duro",
            "aprendizaje",
            "potencial",
        ],
        img: "74.jpg",
    },
    {
        nombre: "Caballero de Oros",
        name: "Knight of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "trabajo duro",
            "responsabilidad",
            "eficiencia",
            "persistencia",
            "diligencia",
        ],
        img: "75.jpg",
    },
    {
        nombre: "Reina de Oros",
        name: "Queen of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "nutrición",
            "practicidad",
            "seguridad",
            "generosidad",
            "bienestar",
        ],
        img: "76.jpg",
    },
    {
        nombre: "Rey de Oros",
        name: "King of Coins",
        categoria: "Los Oros",
        category: "The Coins",
        representa: [
            "abundancia",
            "liderazgo",
            "seguridad",
            "éxito",
            "prosperidad",
        ],
        img: "77.jpg",
    },
]
